import { z } from "zod";
import type { CarWording, Policy } from "~/lib/db/types";
import type { BrokerFeeLineInput } from "~/lib/pdf/merge-fields";
import type { DocumentTemplate } from "~/lib/pdf/templates";

export const PDF_RENDER_CONTRACT_VERSION = 1 as const;
export const PDF_RENDER_PATH = "/v1/render-policy-pdf";
export const MAX_PDF_RENDER_REQUEST_BYTES = 12 * 1024 * 1024;
export const MAX_PDF_RENDER_RESPONSE_BYTES = 16 * 1024 * 1024;

export type PdfRenderRequest = {
  contractVersion: typeof PDF_RENDER_CONTRACT_VERSION;
  requestId: string;
  templateKey: string;
  policy: Policy;
  mergeInputs?: Record<string, string>;
  template: DocumentTemplate;
  wordingCatalogue?: CarWording[];
  brokerFeeLines?: BrokerFeeLineInput[];
};

function isStructuredObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const policyRenderSchema = z.custom<Policy>(
  (value) =>
    isStructuredObject(value) &&
    typeof value.policyId === "string" &&
    value.policyId.length > 0 &&
    typeof value.policyNumber === "string" &&
    isStructuredObject(value.car),
  "Invalid policy render snapshot",
);

const documentTemplateRenderSchema = z.custom<DocumentTemplate>(
  (value) =>
    isStructuredObject(value) &&
    typeof value.key === "string" &&
    Array.isArray(value.mergeFields) &&
    isStructuredObject(value.template),
  "Invalid document template",
);

const carWordingRenderSchema = z.custom<CarWording>(
  (value) =>
    isStructuredObject(value) &&
    typeof value.carWordingId === "number" &&
    typeof value.subject === "string" &&
    typeof value.content === "string",
  "Invalid wording catalogue entry",
);

const brokerFeeRenderSchema = z.custom<BrokerFeeLineInput>(
  (value) =>
    isStructuredObject(value) &&
    typeof value.name === "string" &&
    typeof value.fee === "number" &&
    typeof value.feeGst === "number",
  "Invalid broker fee entry",
);

/**
 * Private service-binding contract. Domain objects are generated by the main
 * Worker, but their outer shape and all unbounded collections are constrained
 * again before the document Worker performs expensive rendering.
 */
export const pdfRenderRequestSchema: z.ZodType<PdfRenderRequest> = z
  .object({
    contractVersion: z.literal(PDF_RENDER_CONTRACT_VERSION),
    requestId: z.string().trim().min(1).max(128),
    templateKey: z.string().trim().min(1).max(64),
    policy: policyRenderSchema,
    mergeInputs: z
      .record(z.string().max(128), z.string().max(1_000_000))
      .optional(),
    template: documentTemplateRenderSchema,
    wordingCatalogue: z.array(carWordingRenderSchema).max(500).optional(),
    brokerFeeLines: z.array(brokerFeeRenderSchema).max(100).optional(),
  })
  .strict();

export const pdfRenderErrorSchema = z.object({
  error: z.enum([
    "invalid_request",
    "payload_too_large",
    "render_failed",
    "method_not_allowed",
    "not_found",
  ]),
  requestId: z.string().max(128).optional(),
});
