-- Target migration scope (CAR policies only).
-- Used by policies.sql, clients.sql, policy-documents.sql, policy-notes.sql, policy-wordings.sql.
--
--   p.ClassCode = 'CAR'
--   AND pc.Status IN (1, 2)   -- Pending, Taken (PolicyCAR.Status)
