-- Target migration: CAR policies with InceptionDate >= 2025-06-01.
-- See scripts/sql/legacy/_target-scope.sql
SELECT
  p.PolicyId AS policyId,
  p.ClientId AS clientId,
  p.PolicyNumber AS policyNumber,
  COALESCE(NULLIF(LTRIM(RTRIM(p.PolicyAction)), ''), 'NEW') AS policyAction,
  pc.Status AS policyStatusId,
  COALESCE(pc.Postcode, '') AS postcode,
  COALESCE(pc.State, 'NSW') AS stateCode,
  p.InceptionDate AS dateStart,
  p.ExpiryDate AS dateEnd,
  COALESCE(NULLIF(LTRIM(RTRIM(p.UnderwriterCode)), ''), 'ATC') AS insurerCode,
  p.CreatedDate AS createdWhen,
  pc.CoverType AS coverTypeId,
  COALESCE(pc.SiteAddress, '') AS siteAddress,
  COALESCE(pc.InsuredName, '') AS insuredName,
  COALESCE(pc.EstimatedTurnover, 0) AS estimatedTurnover,
  COALESCE(pc.BusinessDescriptionText, '') AS businessActivities,
  COALESCE(pc.InsuredContracts, '') AS insuredContracts,
  COALESCE(pc.GeographicalScope, '') AS geographicalScopes,
  COALESCE(pc.PlantEquipment, 0) AS plantEquipment,
  COALESCE(pc.ExistingStructures, 0) AS existingStructure,
  COALESCE(pc.DisplayHomes, 0) AS displayHomes,
  COALESCE(pc.NumberOfClaimLast3Years, 0) AS claimsCountLast3Years,
  COALESCE(pc.AnyClaimsExceed20k, 0) AS anyClaimsExceed20k,
  COALESCE(pc.Confirmation, 0) AS declarationConfirmed,
  COALESCE(pc.Section1Value, 0) AS contractWorksSumInsured,
  COALESCE(pc.Section2Value, 1) AS liabilityLimitBand,
  COALESCE(pc.HoldCurrentContractWorks, 0) AS hasExistingContractWorksCover,
  COALESCE(pc.CurrentInsurer, '') AS currentInsurer,
  CASE pc.CoverType
    WHEN 1 THEN COALESCE(NULLIF(pc.MaximumConstructionPeriod, 0), 18)
    ELSE COALESCE(NULLIF(pc.MaximumConstructionPeriod, 0), 12)
  END AS maximumConstructionPeriod,
  COALESCE(NULLIF(pc.MaximumMaintenancePeriod, 0), 12) AS maximumMaintenancePeriod,
  COALESCE(pc.Section1ExistingStructure, 0) AS contractWorksExistingStructurePremium,
  COALESCE(pc.Section1DisplayHomes, 0) AS contractWorksDisplayHomesPremium,
  COALESCE(pc.DoNotCalculate, 0) AS manualTaxOverride,
  pc.Section1BeforeBasePremium AS contractWorksCalculatedBasePremium,
  pc.Section1TrueBasePremium AS contractWorksBasePremium,
  pc.Section1PlantEquipment AS contractWorksPlantPremium,
  pc.Section1PlantESL AS contractWorksPlantESL,
  pc.Section1ESL AS contractWorksESL,
  pc.Section1GST AS contractWorksGST,
  pc.Section1SD AS contractWorksStampDuty,
  pc.Section1TerrorismPremium AS contractWorksTerrorismPremium,
  pc.Section1PlantTerrorismPremium AS contractWorksPlantTerrorismPremium,
  pc.Section1TotalPremium AS contractWorksTotalPremium,
  pc.Section2BeforeBasePremium AS liabilityCalculatedBasePremium,
  pc.Section2TrueBasePremium AS liabilityBasePremium,
  pc.Section2ESL AS liabilityESL,
  pc.Section2GST AS liabilityGST,
  pc.Section2SD AS liabilityStampDuty,
  pc.Section2TotalPremium AS liabilityTotalPremium,
  pc.OriginalCombinedBrokerFee AS combinedBrokerFee,
  pc.OriginalTotalPremium AS originalTotalPremium,
  pc.CAR_PriceFile_ID AS priceId,
  pc.CAR_StampDuty_ID AS stampDutyId,
  pc.CAR_ESL_ID AS eslId,
  pc.PlantRate AS plantRate,
  pc.ESLRate AS eslRate,
  pc.ESLPlantRate AS plantEslRate,
  pc.SDRateSection1 AS contractWorksStampDutyRate,
  pc.SDRateSection2 AS liabilityStampDutyRate,
  pc.Section1Rate AS contractWorksAppliedRate,
  pc.Section2Rate AS liabilityAppliedRate,
  pc.Section1MinPrem AS contractWorksMinPremium,
  pc.Section2MinPrem AS liabilityMinPremium,
  pc.PlantMinPrem AS plantValueMin,
  pc.PlantMaxPrem AS plantValueMax,
  pc.TerrorismRate AS terrorismRate,
  pc.Adjusted AS hasAdjustment,
  pc.AdjustedTurnover AS adjustedTurnover,
  pc.StampDutyExempt AS stampDutyExempt,
  pc.AdjustedTotalPremium AS adjustedTotalPremium,
  pc.AdjustedDate AS adjustedDate,
  pc.AdjustedSection1TrueBasePremium AS adjustedSection1TrueBasePremium,
  pc.AdjustedSection1TerrorismPremium AS adjustedSection1TerrorismPremium,
  pc.AdjustedSection1ESL AS adjustedSection1Esl,
  pc.AdjustedSection1GST AS adjustedSection1Gst,
  pc.AdjustedSection1SD AS adjustedSection1Sd,
  pc.AdjustedSection1TotalPremium AS adjustedSection1TotalPremium,
  pc.AdjustedSection2TrueBasePremium AS adjustedSection2TrueBasePremium,
  pc.AdjustedSection2ESL AS adjustedSection2Esl,
  pc.AdjustedSection2GST AS adjustedSection2Gst,
  pc.AdjustedSection2SD AS adjustedSection2Sd,
  pc.AdjustedSection2TotalPremium AS adjustedSection2TotalPremium,
  pc.TotalSection1TrueBasePremium AS totalSection1TrueBasePremium,
  pc.TotalSection1TerrorismPremium AS totalSection1TerrorismPremium,
  pc.TotalSection1ESL AS totalSection1Esl,
  pc.TotalSection1GST AS totalSection1Gst,
  pc.TotalSection1SD AS totalSection1Sd,
  pc.TotalSection1TotalPremium AS totalSection1TotalPremium,
  pc.TotalSection2TrueBasePremium AS totalSection2TrueBasePremium,
  pc.TotalSection2ESL AS totalSection2Esl,
  pc.TotalSection2GST AS totalSection2Gst,
  pc.TotalSection2SD AS totalSection2Sd,
  pc.TotalSection2TotalPremium AS totalSection2TotalPremium,
  pc.TotalTotalPremium AS totalTotalPremium,
  sl.RemovalOfDebris AS removalOfDebris,
  sl.ExpeditingExpenses AS expeditingExpenses,
  sl.ProfessionalFees AS professionalFees,
  sl.MitigationExpenses AS mitigationExpenses,
  sl.SearchAndLocateCosts AS searchAndLocateCosts,
  sl.PlantHireCharges AS plantHireCharges,
  sl.ClaimsPreparationCosts AS claimsPreparationCosts,
  sl.GovernmentCosts AS governmentCosts,
  sl.InflationProtection AS inflationProtection,
  sl.EmployeesProperty AS employeesProperty,
  sl.MaterialsInOffSiteStorage AS materialsInOffSiteStorage,
  sl.Transit AS transit,
  sl.ExcludedContracts1 AS excludedContracts1,
  sl.ExcludedContracts2 AS excludedContracts2,
  sl.ExcludedContracts3 AS excludedContracts3,
  ex.ExcessSection1A AS excessSection1A,
  ex.ExcessSection1B AS excessSection1B,
  ex.ExcessSection1C AS excessSection1C,
  ex.ExcessSection1D AS excessSection1D,
  ex.ExcessSection1E AS excessSection1E,
  ex.ExcessSection2A AS excessSection2A,
  ex.ExcessSection2B AS excessSection2B,
  ex.ExcessSection2C AS excessSection2C,
  ex.ExcessSection2D AS excessSection2D,
  ex.ExcessSection2E AS excessSection2E,
  ex.ExcessSection2F AS excessSection2F,
  ex.ExcessAdditionalNotes AS excessAdditionalNotes
FROM dbo.Policy p
INNER JOIN dbo.PolicyCAR pc ON pc.PolicyId = p.PolicyId
LEFT JOIN dbo.PolicyCARSubLimitWording sl ON sl.PolicyId = p.PolicyId
LEFT JOIN dbo.PolicyCARExcess ex ON ex.PolicyId = p.PolicyId
WHERE p.ClassCode = 'CAR'
  AND p.InceptionDate >= '2025-06-01'
ORDER BY p.PolicyId;
