/** Shared audit action codes — safe for client + server imports. */
export const AUDIT_ACTIONS = [
  "auth.login",
  "auth.logout",
  "client.create",
  "client.update",
  "client.delete",
  "policy.create",
  "policy.save",
  "policy.clone",
  "policy.delete",
  "policy.status_change",
  "policy.adjust",
  "policy.documents_generate",
  "policy.documents_email",
  "user.create",
  "user.update",
  "user.disable",
  "user.enable",
  "user.delete",
  "ar.create",
  "ar.update",
  "ar.delete",
  "settings.feature_toggle",
  "settings.email_template",
  "settings.library_document_upload",
  "settings.library_document_delete",
  "settings.library_document_label",
  "settings.library_document_cover_types",
  "price.create",
  "price.update",
  "price.delete",
  "report.export",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number] | (string & {});
