/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.pdf.jsonc --env-file=workers/documents-local.env --include-runtime=false --env-interface=PdfWorkerEnv workers/pdf/env.d.ts` (hash: 643a13e45b5df96ddde3a903f25f3dc4)
interface __BaseEnv_PdfWorkerEnv {
	ASSETS: Fetcher;
	WORKER_SHARED_SECRET: "{{ secrets.WORKER_SHARED_SECRET }}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_PdfWorkerEnv {}
}
interface PdfWorkerEnv extends __BaseEnv_PdfWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORKER_SHARED_SECRET">> {}
}
