// Generated by Wrangler by running `wrangler types --config=wrangler.pdf.jsonc --env-file=workers/documents-local.env --include-runtime=false --env-interface=PdfWorkerEnv workers/pdf/env.d.ts` (hash: 7aca718c63f0ab34fcc30da79c9c9788)
interface __BaseEnv_PdfWorkerEnv {
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_PdfWorkerEnv {}
}
interface PdfWorkerEnv extends __BaseEnv_PdfWorkerEnv {}
