// Generated by Wrangler by running `wrangler types --config=wrangler.documents.jsonc --env-file=workers/documents-local.env --include-runtime=false --env-interface=DocumentWorkerEnv workers/document-worker-env.d.ts` (hash: 2fee162be88897338df4f6e052bb17b3)
interface __BaseEnv_DocumentWorkerEnv {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./documents");
	}
	interface Env extends __BaseEnv_DocumentWorkerEnv {}
}
interface DocumentWorkerEnv extends __BaseEnv_DocumentWorkerEnv {}
